deploy:dev:
  stage: deploy
  environment:
    name: dev
    url: https://dev-$PANTHEON_SITE.pantheonsite.io/
  script:
    - git remote add pantheon https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/ohmadyt/ohmadyt.git
    - git push pantheon master --force

    - terminus remote:drush $PANTHEON_SITE.dev -- cr
    - terminus remote:drush $PANTHEON_SITE.dev -- updb
    - terminus remote:drush $PANTHEON_SITE.dev -- cim
  only:
    - main