deploy:dev:
  stage: deploy
  environment:
    name: dev
    url: https://dev-$PANTHEON_SITE.pantheonsite.io/
  script:
    - git remote add pantheon $PANTHEON_GIT_URL
    - git push pantheon main:master --force

    - terminus remote:drush $PANTHEON_SITE.dev -- cr
    - terminus remote:drush $PANTHEON_SITE.dev -- updb
    - terminus remote:drush $PANTHEON_SITE.dev -- cim
  only:
    - main
