image: registry.gitlab.com/ataylorme/pantheon-gitlab-blog-demo:latest

stages:
  - deploy

before_script:
  # See https://docs.gitlab.com/ee/ci/ssh_keys/
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p $HOME/.ssh && echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name "Gitlab CI"
  # Install Terminus
  - curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install
  - 'which terminus'
  - export PATH=$PATH:$HOME/.terminus/bin
  - terminus auth:login --machine-token=${PANTHEON_MACHINE_TOKEN}

deploy:dev:
  stage: deploy
  environment:
    name: dev
    url: https://dev-$PANTHEON_SITE.pantheonsite.io/
  script:
    - git clone $CI_REPOSITORY_URL repo
    - cd repo
    - git checkout main
    - git remote add pantheon $PANTHEON_GIT_URL
    - git push pantheon main:master --force

    - terminus remote:drush $PANTHEON_SITE.dev -- cr
    - terminus remote:drush $PANTHEON_SITE.dev -- updb
    - terminus remote:drush $PANTHEON_SITE.dev -- cim
  only:
    - main
