adding:
  dependencies:
    config:
      - field.field.node.photo.domain_access
      - field.field.node.photo.field_domain_access
  content:
    domain_access:
      type: options_buttons
      weight: 26
      region: content
      settings: {  }
      third_party_settings: {  }
  hidden:
    field_domain_access: true
removing: {  }
