adding:
  dependencies:
    config:
      - field.field.node.poster.domain_access
      - field.field.node.poster.field_domain_access
  content:
    domain_access:
      type: options_buttons
      weight: 122
      region: content
      settings: {  }
      third_party_settings: {  }
  hidden:
    field_domain_access: true
removing: {  }
