adding:
  dependencies:
    config:
      - field.field.block_content.basic.domain_access
  content:
    domain_access:
      type: options_buttons
      weight: 26
      region: content
      settings: {  }
      third_party_settings: {  }
removing: {  }
