adding:
  dependencies:
    config:
      - field.field.node.page.field_domain_access
  content:
    field_domain_access:
      type: options_buttons
      weight: 11
      region: content
      settings: {  }
      third_party_settings: {  }
removing: {  }
