adding:
  dependencies:
    config:
      - field.field.user.user.field_domain_access
      - field.field.user.user.field_domain_admin
  content:
    field_domain_access:
      type: options_buttons
      weight: 40
      region: content
      settings: {  }
      third_party_settings: {  }
    field_domain_admin:
      type: options_buttons
      weight: 50
      region: content
      settings: {  }
      third_party_settings: {  }
removing: {  }
