adding:
  dependencies:
    config:
      - field.field.node.massmedia.field_domain_access
  content:
    field_domain_access:
      type: entity_reference_autocomplete
      weight: 12
      region: content
      settings:
        match_operator: CONTAINS
        match_limit: 10
        size: 60
        placeholder: ''
      third_party_settings: {  }
removing: {  }
