adding:
  status: true
  dependencies:
    config:
      - field.storage.node.field_domain_access
  description: 'Find and manage content.'
  display:
    default:
      display_title: Master
      display_options:
        fields:
          title:
            label: Title
          field_domain_access:
            id: field_domain_access
            table: node__field_domain_access
            field: field_domain_access
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: domain_access_field
            label: Domain(s)
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: true
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: target_id
            type: entity_reference_label
            settings:
              link: true
            group_column: target_id
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
          name:
            label: Author
          status:
            label: Status
            settings:
              format_custom_false: Unpublished
              format_custom_true: Published
          changed:
            label: Updated
          operations:
            label: Operations
        pager:
          options:
            tags:
              next: 'Next ›'
              previous: '‹ Previous'
              first: '« First'
              last: 'Last »'
        exposed_form:
          options:
            submit_button: Filter
            reset_button_label: Reset
            exposed_sorts_label: 'Sort by'
            sort_asc_label: Asc
            sort_desc_label: Desc
        empty:
          area_text_custom:
            content: 'No content available.'
        arguments:
          field_domain_access_target_id:
            exception:
              title: All
        filters:
          status:
            expose:
              label: Status
            group_info:
              label: 'Published status'
              group_items:
                -
                  title: Published
          type:
            expose:
              label: Type
          title:
            expose:
              label: Title
          langcode:
            expose:
              label: Language
    page_1:
      display_options:
        title: Content
        filters:
          status:
            expose:
              label: Status
            group_info:
              label: 'Published status'
              group_items:
                -
                  title: Published
          type:
            expose:
              label: Type
          title:
            expose:
              label: Title
          langcode:
            expose:
              label: Language
        menu:
          title: Content
        tab_options:
          title: Content
          description: 'Find and manage content'
    page_2:
      display_options:
        filters:
          status:
            expose:
              label: Status
            group_info:
              label: 'Published status'
              group_items:
                -
                  title: Published
          type:
            expose:
              label: Type
          title:
            expose:
              label: Title
          langcode:
            expose:
              label: Language
          field_domain_access_target_id:
            expose:
              label: Domain
removing:
  status: false
  description: 'Пошук матеріалів і керування ними.'
  display:
    default:
      display_title: Головне
      display_options:
        fields:
          title:
            label: Заголовок
          name:
            label: Автор
          status:
            label: Стан
            settings:
              format_custom_false: Неопубліковано
              format_custom_true: Опубліковано
          changed:
            label: Оновлено
          operations:
            label: Операції
        pager:
          options:
            tags:
              next: 'Наступна ›'
              previous: '‹ Попередня'
              first: '« Перша'
              last: 'Остання »'
        exposed_form:
          options:
            submit_button: Фільтр
            reset_button_label: Скинути
            exposed_sorts_label: 'Впорядкувати за'
            sort_asc_label: Зрост
            sort_desc_label: Спад
        empty:
          area_text_custom:
            content: 'Матеріали відсутні.'
        arguments:
          field_domain_access_target_id:
            exception:
              title: Все
        filters:
          status:
            expose:
              label: Стан
            group_info:
              label: 'Стан публікації'
              group_items:
                -
                  title: Опубліковано
          type:
            expose:
              label: Тип
          title:
            expose:
              label: Заголовок
          langcode:
            expose:
              label: Мова
    page_1:
      display_options:
        title: Вміст
        filters:
          status:
            expose:
              label: Стан
            group_info:
              label: 'Стан публікації'
              group_items:
                -
                  title: Опубліковано
          type:
            expose:
              label: Тип
          title:
            expose:
              label: Заголовок
          langcode:
            expose:
              label: Мова
        menu:
          title: Вміст
        tab_options:
          title: Вміст
          description: 'Пошук матеріалів та керування ними'
    page_2:
      display_options:
        filters:
          status:
            expose:
              label: Стан
            group_info:
              label: 'Стан публікації'
              group_items:
                -
                  title: Опубліковано
          type:
            expose:
              label: Тип
          title:
            expose:
              label: Заголовок
          langcode:
            expose:
              label: Мова
          field_domain_access_target_id:
            expose:
              label: Домен
