adding:
  dependencies:
    config:
      - field.field.node.anonsy_podiy.domain_access
      - field.field.node.anonsy_podiy.field_domain_access
  hidden:
    domain_access: true
    field_domain_access: true
removing: {  }
