adding:
  status: true
  dependencies:
    config:
      - field.storage.user.field_domain_access
  description: 'Find and manage people interacting with your site.'
  display:
    default:
      display_title: Master
      display_options:
        title: People
        fields:
          user_bulk_form:
            label: 'Bulk update'
          name:
            label: Username
          status:
            label: Status
            settings:
              format_custom_false: Blocked
              format_custom_true: Active
          roles_target_id:
            label: Roles
          field_domain_access:
            id: field_domain_access
            table: user__field_domain_access
            field: field_domain_access
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: domain_access_field
            label: Domain(s)
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: true
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: target_id
            type: entity_reference_label
            settings:
              link: false
            group_column: target_id
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
          created:
            label: 'Member for'
          access:
            label: 'Last access'
            settings:
              future_format: '@interval hence'
              past_format: '@interval ago'
          operations:
            label: Operations
        pager:
          options:
            tags:
              next: 'Next ›'
              previous: '‹ Previous'
              first: '« First'
              last: 'Last »'
            expose:
              items_per_page_label: 'Items per page'
              items_per_page_options_all_label: '- All -'
              offset_label: Offset
        exposed_form:
          options:
            submit_button: Filter
            reset_button_label: Reset
            exposed_sorts_label: 'Sort by'
            sort_asc_label: Asc
            sort_desc_label: Desc
        empty:
          area_text_custom:
            content: 'No people available.'
        filters:
          combine:
            expose:
              label: 'Name or email contains'
          roles_target_id:
            expose:
              label: Role
          permission:
            expose:
              label: Permission
          status:
            group_info:
              label: Status
              group_items:
                -
                  title: Active
                -
                  title: Blocked
        use_more_text: more
    page_1:
      display_options:
        arguments:
          field_domain_access_target_id:
            exception:
              title: All
        menu:
          title: List
          description: 'Find and manage people interacting with your site.'
        tab_options:
          title: People
          description: 'Manage user accounts, roles, and permissions.'
    page_2:
      display_options:
        filters:
          combine:
            expose:
              label: 'Name or email contains'
          roles_target_id:
            expose:
              label: Role
          permission:
            expose:
              label: Permission
          status:
            group_info:
              label: Status
              group_items:
                -
                  title: Active
                -
                  title: Blocked
          field_domain_access_target_id:
            expose:
              label: Domain
removing:
  status: false
  description: 'Пошук людей, які взаємодіють з сайтом, і керування ними.'
  display:
    default:
      display_title: Головне
      display_options:
        title: Люди
        fields:
          user_bulk_form:
            label: 'Масове оновлення'
          name:
            label: "Ім'я користувача"
          status:
            label: Стан
            settings:
              format_custom_false: Заблоковано
              format_custom_true: Активно
          roles_target_id:
            label: Ролі
          created:
            label: 'Зареєстрований вже'
          access:
            label: 'Останній доступ'
            settings:
              future_format: '@interval віднині'
              past_format: '@interval тому'
          operations:
            label: Операції
        pager:
          options:
            tags:
              next: 'Наступна ›'
              previous: '‹ Попередня'
              first: '« Перша'
              last: 'Остання »'
            expose:
              items_per_page_label: 'Елементів на сторінку'
              items_per_page_options_all_label: '- Усе -'
              offset_label: Зміщення
        exposed_form:
          options:
            submit_button: Фільтр
            reset_button_label: Скинути
            exposed_sorts_label: 'Впорядкувати за'
            sort_asc_label: Зрост
            sort_desc_label: Спад
        empty:
          area_text_custom:
            content: 'Люди відсутні.'
        filters:
          combine:
            expose:
              label: "Ім'я чи електронна адреса містять"
          roles_target_id:
            expose:
              label: Роль
          permission:
            expose:
              label: Повноваження
          status:
            group_info:
              label: Стан
              group_items:
                -
                  title: Активно
                -
                  title: Заблоковано
        use_more_text: ще
    page_1:
      display_options:
        arguments:
          field_domain_access_target_id:
            exception:
              title: Все
        menu:
          title: Список
          description: 'Пошук людей, які взаємодіють з сайтом, і керування ними.'
        tab_options:
          title: Люди
          description: 'Керування обліковими записами, ролями та повноваженнями.'
    page_2:
      display_options:
        filters:
          combine:
            expose:
              label: "Ім'я чи електронна адреса містять"
          roles_target_id:
            expose:
              label: Роль
          permission:
            expose:
              label: Повноваження
          status:
            group_info:
              label: Стан
              group_items:
                -
                  title: Активно
                -
                  title: Заблоковано
          field_domain_access_target_id:
            expose:
              label: Домен
