adding:
  dependencies:
    config:
      - field.field.node.video.domain_access
      - field.field.node.video.field_domain_access
  hidden:
    domain_access: true
    field_domain_access: true
removing: {  }
