<?php

/**
 * @file
 * Adding migrate preparing.
 */

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Row;
use Drupal\migrate\Plugin\MigrationInterface;

/**
 * Implements hook_migrate_prepare_row().
 */
function ohmatdyt_import_migrate_ohmatdyt_department_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  // Получаем базовый путь к модулю
  $modulePath = \Drupal::service('extension.list.module')->getPath('ohmatdyt_import');

  // Формируем путь к файлу departments.json
  $jsonFilePath = $modulePath . '/src/departments.json';

  $jsonData = file_get_contents($jsonFilePath);
  // Преобразуем JSON данные в ассоциативный массив
  $data = json_decode($jsonData, true);

  // Получаем ссылку на массив "data"
  $dataArray = &$data['data'];

  // Проходимся по каждой записи в массиве "data"
  foreach ($dataArray as &$record) {
    // Получаем текущее значение mi_data_id
    $miDataId = $record[0];

    // Оставляем только последние 7 цифр
    $miDataId = substr($miDataId, -7);

    // Обновляем значение mi_data_id
    $record[0] = $miDataId;

    // Получаем текущее значение parentUnitID
    $parentUnitID = $record[4];

    // Оставляем только последние 7 цифр
    $parentUnitID = substr($parentUnitID, -7);

    // Обновляем значение parentUnitID
    $record[4] = $parentUnitID;
  }

  // Преобразуем данные обратно в JSON формат
  $newJsonData = json_encode($data, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);

  // Записываем измененные данные обратно в файл
  file_put_contents($jsonFilePath, $newJsonData);

  // Получаем сервис Messenger из контейнера сервисов
  $messenger = \Drupal::service('messenger');

  // Выводим сообщение
  $messenger->addMessage('Изменения внесены успешно!');
}
